---
- name: Update home-assistant configuration
  git:
    repo: 'file://{{ home_assistant_git_repo }}'
    dest: '{{ automation_mounted_directory }}/configs/{{ docker_ha_container_name}}'
    version: master
    force: yes
  become_user: automation

# need to make this smarter so it runs after the docker tasks
#- name: Install OpenCV
#  command: sudo docker exec -i home-assistant /bin/bash -c 'pip install opencv-python'
#  notify: restart home-assistant
