---
- name: Update home-assistant configuration
  git:
    repo: '{{ home_assistant_git_repo }}'
    dest: '{{ automation_mounted_directory }}/configs/{{ docker_ha_container_name}}'
    version: development
    force: yes

- name: Install OpenCV
  command: sudo docker exec -i home-assistant /bin/bash -c 'pip install opencv-python'
  when: haStarted.changed
  notify: restart home-assistant