---

- name: Create Configs Directory
  file:
    name: '{{ automation_mounted_directory }}/configs'
    state: directory

- include_tasks: ha-triggers.yml
- include_tasks: home-assistant.yml
- include_tasks: nodered.yml