---
- name: 'Make sure node-red config exists'
  file:
    path: '{{ automation_mounted_directory }}/configs/{{ docker_nodered_container_name }}'
    state: directory
    mode: 0775
    owner: automation
    group: automation
