---
- name: Restart Home-Assistant
  docker_container:
    name: '{{ docker_ha_container_name }}'
    image: homeassistant/home-assistant:latest
    state: restarted

- name: Start STT
  command: 'docker exec {{ docker_stt_container_name }} /bin/bash -l -c "/opt/start.sh -y /opt/models/{{ stt_model_name }}"'
