---
- name: restart home-assistant
  systemd:
    name: docker-home-assistant
    state: restarted
    enabled: yes
    daemon_reload: yes


- name: Start STT
  command: 'docker exec {{ docker_stt_container_name }} /bin/bash -l -c "/opt/start.sh -y /opt/models/{{ stt_model_name }}"'
