---
- name: restart '{{ item.key }}'
  service:
    name: '{{ item.key }}'
    state: restarted
  with_dict: docker_containers

- name: Start STT
  command: 'docker exec {{ docker_stt_container_name }} /bin/bash -l -c "/opt/start.sh -y /opt/models/{{ stt_model_name }}"'
